### ISSUE TITLE
[2024 Symposium] Synthetic Data 

### ISSUE THREAD

**Issue by kzollove** [OHDSI/GIS#345]
Items to be completed in support of Synthetic Data generation in advance of the OHDSI Symposium

- Consider using synthetic data with generated addresses in 3 locations (domestic & international)
    - Consider Boston, Sao Paolo, China, and a European city

Only using locations at the city level; reference global PM2.5 data 1998-2016; synthetic patients take city locations

In workshop: brief description of the synthetic dataset, minimal detail on location generation (keyword minimal)

**Comment by kzollove** [comment]
Jared loaded all Belgian place data into Nominatim, has workflow in place, will shift to one of target cities (likely start with Boston)

Geocoded needs to take place in a pre-step - will likely need to be its own containerized process

TODO: Brief written description on how the Tufts Syntegra database will be divided into parts to represent separate EHRs

**Comment by kzollove** [comment]
Update from Jared: Geocoded a subset of Boston addresses using Nominatim; scripted, references docker images that downloads from Open Street Maps or makes direct calls to Nominatim API (for downloading the OSM files, not for geocoding the addresses)

Geocoding will be added to the containerization with option to use DeGauss in US or Nominatim for outside of the US

Hitting issues with the load_variable step; we will chat outside of meeting to resolve

**Comment by kzollove** [comment]
TODO a high level explainer on how to produce fake geocoded locations to link to real PM2.5 data

**Comment by kzollove** [comment]
load_exposure no longer working @kzollove

**Comment by kzollove** [comment]
> load_exposure no longer working @kzollove

Resolved

**Comment by kzollove** [comment]
Send Jared a list of city names and a single coordinate for each city represented in the SEDACS dataset @tibbben

**Comment by kzollove** [comment]
Jared created locations for the cities that Tim sent. Using the Tufts syntegra dataset to create mock EHRs

Jared will add synthetic Location/ Location_history with links back to syntegra to GIS repo

**Comment by jshoughtaling** [comment]
# GIS-Specific Synthetic Dataset

## Description

The purpose of the GIS-specific synthetic data is to provide the foundation for an end-to-end demonstration that combines electronic health record (EHR) data in OMOP-CDM format with (1) [datasets containing geospatial variables](https://github.com/OHDSI/GIS/blob/main/inst/csv/data_source.csv) (e.g. average levels of pollutants in a region), and (2) [terminology](https://github.com/TuftsCTSI/CVB/tree/main/GIS/Ontology) to capture those variables in an OMOP-CDM format.

This particular dataset is an augmented subset (~7000 individuals) of the full (~500k individuals) Tufts Synthetic Dataset, with a particular focus on individuals who have Chronic Obstructive Pulmonary Disorder (COPD). We conducted the augmentation using the [**gaiaCore**](https://github.com/OHDSI/GIS) toolchain developed by the GIS workgroup, combined with a location assignment approach that distributed a specified ratio of COPD vs non-COPD synthetic individuals to a subset of global cities with wide ranging values of PM<sub>2.5</sub>. Once assigned, we derived an [EXPOSURE_OCCURRENCE](https://ohdsi.github.io/GIS/gaia-datamodels.html#exposure_occurrence) table using pre-assigned 2B+ concept_id values that we were able to reference later in the downstream analytics workflow. The details of this augmentation process, including code and references, are described at length in the sections below.

### Tufts Synthetic Data

The Tufts Synthetic Dataset is a set of completely synthetic electronic health record (EHR) data for approximately 500,000 fake patients. It was produced in 2021 through a collaboration between Syntegra, Inc. and Tufts Medical Center. A novel deep learning transformer model (the kind of model used by modern LLMs) developed by Syntegra was used to generate synthetic clinical data including data on visits, conditions, drugs, measurements, procedures, observation and device exposures. The model was trained on a version of the Tufts Research Data Warehouse (TRDW) that contained longitudinal EHR data on patients who received care at Tufts Medical Center. Both the TRDW training data and the synthetic data conform to version 5.3 of the OMOP common data model. _Note that for the purposes of this GIS demonstration, we converted the data to OMOP version 5.4._

 An expert determination of the HIPAA compliance of the dataset was conducted by Mirador Analytics Ltd. in 2022 (Report No SYN222P1a). It confirmed that the data are safe to share and to use without posing a risk to patient privacy. Analyses by Syntegra and Tufts Medical Center researchers confirmed the statistically realistic properties of the data through comparisons of descriptive statistics, treatment pathways and prediction models on the synthetic and real data. The data also contain realistic data quality errors. This realism makes the dataset a useful asset in training researchers to work with OMOP-shaped data in all phases of observational research from data quality assessment through analysis using the tools and practices of the Observational Health Data Science and Informatics (OHDSI) community and other OMOP-using communities. Its realism and format also make it useful for testing software designed to work with OMOP-shaped data, and for preparing study packages that use OHDSI tools to define and conduct full observational research studies. 

### PM<sub>2.5</sub> Dataset

The Annual PM<sub>2.5</sub> Concentrations for Countries and Urban Areas, 1998-2016, consists of mean concentrations of particulate matter (PM<sub>2.5</sub>) for countries and urban areas (see [manual](https://sedac.ciesin.columbia.edu/downloads/docs/sdei/sdei-annual-pm2-5-concentrations-countries-urban-areas-v1-1998-2016-documentation.pdf) for more details). The PM<sub>2.5</sub> data are from the Global Annual PM2.5 Grids from MODIS, MISR and SeaWiFS Aerosol Optical Depth (AOD) with GWR, 1998-2016. The urban areas are from the Global Rural-Urban Mapping Project, Version 1 (GRUMPv1): Urban Extent Polygons, Revision 02, and its time series runs from 1998 to 2016. The country averages are population-weighted such that concentrations in populated areas count more toward the country average than concentrations in less populated areas, and its time series runs from 2008 to 2015.

### Analytic Use Case

While the analytic approach and associated results are described in more detail [elsewhere](), the general motivation for creating this dataset was to be able to support a patient-level prediction (PLP) model to predict the risk of COPD for a particular individual given pollutant levels in their city of residence together with their EHR record.

## Data Processing

We first converted the Tufts Synthetic Data to OMOP version 5.4 using a set of SQL scripts against a Databricks instance. In the same schema, we inserted the GIS terminology into the standard OMOP vocabulary tables, and then filled the LOCATION, LOCATION_HISTORY, and EXPOSURE_OCCURRENCE tables as described in the subsections below.

### COPD Cohort Definition

In order to capture those patients fitting our desired COPD phenotype, we used a [general representation of COPD]

### Location Assignment

We referred to two recent works that describe (1) the general, global prevalence of COPD as of 2023, and (2) the relationship between prevalence of COPD local concentrations of PM<sub>2.5</sub>:
1. [Boers, Elroy, et al. "Global burden of chronic obstructive pulmonary disease through 2050." JAMA Network Open 6.12 (2023): e2346598-e2346598.](https://jamanetwork.com/journals/jamanetworkopen/article-abstract/2812622)
2. [Liu, Sha, et al. "Association between exposure to ambient particulate matter and chronic obstructive pulmonary disease: results from a cross-sectional study in China." Thorax 72.9 (2017): 788-795.](https://thorax.bmj.com/content/72/9/788.short)

From these two papers, we derived a **very crude** relationship between Odds Ratios (OR) of COPD versus concentration of PM<sub>2.5</sub>:

![Estimated_OR](https://github.com/user-attachments/assets/c2b37837-231b-4dd8-a915-f00e41d7ad30)

We then selected 20 cities evenly distributed along this concentration range using the medians of their 18 year annual concentration data in the PM<sub>2.5</sub> dataset. With these 20 cities, we used the estimated OR relationship above to calculate a crude distribution of cases versus non-cases such that the total individuals with COPD in the Tufts Synthetic Dataset were all included. 

| CITY | COUNTRY | LATITUTE | LONGITUDE | MEDIAN PM2.5 | CASE  | NOT CASE | OR |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| BULANDSHAHR | INDIA | 28.40449524 | 77.85832214 | 95.94 | 121 | 233 | 4.67 |
| WANGDU | CHINA | 38.71282768 | 115.1666565 | 85.59 | 115 | 239 | 4.330 |
| JINGHAI | CHINA | 38.93782806 | 116.9374886 | 74.41 | 109 | 244 | 4.02 |
| SARSAWAN | INDIA | 30.00217158 | 77.34992132 | 63.93 | 100 | 253 | 3.56 |
| DOKKHAMTAI | THAILAND | 19.17445183 | 99.96205373 | 55.26 | 88 | 265 | 2.99 |
| LAHORE | PAKISTAN | 31.49387074 | 74.35156631 | 47.86 | 77 | 277 | 2.50 |
| KINSHASA | CONGO DR | -4.397176266 | 15.33447051 | 35.82 | 53 | 300 | 1.59 |
| JOHANNESBURG | SOUTH AFRICA | -26.17050266 | 28.0999918 | 33.24 | 50 | 303 | 1.49 |
| KATOWICE | POLAND | 50.22116089 | 18.97915935 | 28.02 | 44 | 309 | 1.28 |
| PAVIA | ITALY | 45.20035744 | 9.183955636 | 25.69 | 41 | 312 | 1.18 |
| HUARMEY | PERU | -10.07883644 | -78.14238828 | 20.18 | 38 | 315 | 1.09 |
| SCHOUWENDUIVELAND | NETHERLANDS | 51.64616013 | 3.924992681 | 17.24 | 38 | 315 | 1.09 |
| FRESNO | USA | 36.69616127 | -119.6958351 | 15.47 | 38 | 315 | 1.09 |
| BUFFALO | USA | 42.89597574 | -78.67471096 | 10.51 | 35 | 318 | 0.99 |
| LAPLAYOSA | ARGENTINA | -32.09550285 | -63.03333855 | 4.98 | 35 | 318 | 0.99 |
| PERTH | AUSTRALIA | -32.03704071 | 115.975156 | 2.14 | 32 | 321 | 0.90 |
| FORKS | USA | 47.94616127 | -124.3791656 | 2.1 | 32 | 321 | 0.90 |
| SITKA | USA | 57.07949448 | -135.3333359 | 0.7 | 29 | 324 | 0.81 |
| ALEXANDRA | NEW ZEALAND | -45.24550247 | 169.4166565 | 0.6 | 29 | 324 | 0.81 |
| SUVA | FIJI | -18.07050228 | 178.4999847 | 0.18 | 27 | 327 | 0.74 |


### Case Sampling

Once defining the case/non-case distribution numbers across the 20 locations, we set out to create a non-COPD individual sub sample from the Tufts Synthetic Dataset with an age and gender distribution aligned with the existing COPD individuals. 

We calculated a rough age distribution of the entire COPD cohort, as well as a gender split, and used these values within a [set of nested subqueries](https://github.com/user-attachments/files/17398785/nonCOPD.txt) to capture a crudely representative cohort without COPD. We then placed these ~6500 non-COPD individuals together with the ~1100 COPD individuals, and then randomly assigned them to the different locations based on the ratios derived above.

### Location History

For the purposes of this demo
